# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/sm8450-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter udon CPH2487 aston sm8450 sm8475 taro,$(TARGET_DEVICE)),)

endif
