# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/sm8450-common/setup-makefiles.sh

$(call inherit-product, vendor/oneplus/sm8450-common/sm8450-common-vendor.mk)
